// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Chronologie documents */
interface ChronologieDocumentData {
    /**
     * Titel field in *Chronologie*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: chronologie.titel
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    titel: prismicT.TitleField;
    /**
     * Slice Zone field in *Chronologie*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: chronologie.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ChronologieDocumentDataSlicesSlice>;
}
/**
 * Slice for *Chronologie → Slice Zone*
 *
 */
type ChronologieDocumentDataSlicesSlice = EintragChronologieSlice;
/**
 * Chronologie document from Prismic
 *
 * - **API ID**: `chronologie`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ChronologieDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ChronologieDocumentData>, "chronologie", Lang>;
/** Content for CV documents */
interface CvDocumentData {
    /**
     * Titel field in *CV*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: cv.titel
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    titel: prismicT.TitleField;
    /**
     * Text field in *CV*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cv.text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
}
/**
 * CV document from Prismic
 *
 * - **API ID**: `cv`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CvDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<CvDocumentData>, "cv", Lang>;
/** Content for Impressum documents */
interface ImpressumDocumentData {
    /**
     * Titel field in *Impressum*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: impressum.titel
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    titel: prismicT.TitleField;
    /**
     * Text field in *Impressum*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: impressum.text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
}
/**
 * Impressum document from Prismic
 *
 * - **API ID**: `impressum`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ImpressumDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ImpressumDocumentData>, "impressum", Lang>;
/** Content for Kontakt documents */
interface KontaktDocumentData {
    /**
     * Titel field in *Kontakt*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: kontakt.titel
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    titel: prismicT.TitleField;
    /**
     * Text field in *Kontakt*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: kontakt.text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
}
/**
 * Kontakt document from Prismic
 *
 * - **API ID**: `kontakt`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type KontaktDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<KontaktDocumentData>, "kontakt", Lang>;
/** Content for Projekt documents */
interface ProjektDocumentData {
    /**
     * Projektname field in *Projekt*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: projekt.projektname
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    projektname: prismicT.RichTextField;
    /**
     * Kategorie Projekt field in *Projekt*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: projekt.kategorie_projekt
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    kategorie_projekt: prismicT.RelationField<"projektkategorie">;
}
/**
 * Projekt document from Prismic
 *
 * - **API ID**: `projekt`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjektDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ProjektDocumentData>, "projekt", Lang>;
/** Content for Projektkategorie documents */
interface ProjektkategorieDocumentData {
    /**
     * Projektkategorie Name field in *Projektkategorie*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: projektkategorie.projektkategorie_name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    projektkategorie_name: prismicT.RichTextField;
}
/**
 * Projektkategorie document from Prismic
 *
 * - **API ID**: `projektkategorie`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjektkategorieDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ProjektkategorieDocumentData>, "projektkategorie", Lang>;
/** Content for Werk documents */
interface WerkDocumentData {
    /**
     * Titel field in *Werk*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: werk.titel
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    titel: prismicT.TitleField;
    /**
     * Beschreibung field in *Werk*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: werk.beschreibung
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    beschreibung: prismicT.RichTextField;
    /**
     * Zugehöriges Projekt field in *Werk*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: werk.zugehoriges_projekt
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    zugehoriges_projekt: prismicT.RelationField<"projekt">;
    /**
     * Kreisel field in *Werk*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: werk.kreisel
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    kreisel: prismicT.ImageField<never>;
    /**
     * Kreisel X Position field in *Werk*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: werk.kreisel_x_position
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    kreisel_x_position: prismicT.NumberField;
    /**
     * Kreisel Y Position field in *Werk*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: werk.kreisel_y_position
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    kreisel_y_position: prismicT.NumberField;
    /**
     * Größe Kreisel in Pixel field in *Werk*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: werk.grosse_kreisel
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    grosse_kreisel: prismicT.NumberField;
    /**
     * Slice Zone field in *Werk*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: werk.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<WerkDocumentDataSlicesSlice>;
}
/**
 * Slice for *Werk → Slice Zone*
 *
 */
type WerkDocumentDataSlicesSlice = ImageUploaderSlice;
/**
 * Werk document from Prismic
 *
 * - **API ID**: `werk`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WerkDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<WerkDocumentData>, "werk", Lang>;
export type AllDocumentTypes = ChronologieDocument | CvDocument | ImpressumDocument | KontaktDocument | ProjektDocument | ProjektkategorieDocument | WerkDocument;
/**
 * Item in BilderHochladen → Items
 *
 */
export interface ImageUploaderSliceDefaultItem {
    /**
     * Bild field in *BilderHochladen → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: image_uploader.items[].bild
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    bild: prismicT.ImageField<never>;
}
/**
 * Default variation for BilderHochladen Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ImageUploader`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageUploaderSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<ImageUploaderSliceDefaultItem>>;
/**
 * Slice variation for *BilderHochladen*
 *
 */
type ImageUploaderSliceVariation = ImageUploaderSliceDefault;
/**
 * BilderHochladen Shared Slice
 *
 * - **API ID**: `image_uploader`
 * - **Description**: `ImageUploader`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageUploaderSlice = prismicT.SharedSlice<"image_uploader", ImageUploaderSliceVariation>;
/**
 * Item in EintragChronologie → Items
 *
 */
export interface EintragChronologieSliceDefaultItem {
    /**
     * Titel field in *EintragChronologie → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: eintrag_chronologie.items[].titel
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    titel: prismicT.RichTextField;
    /**
     * Beschreibung field in *EintragChronologie → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: eintrag_chronologie.items[].beschreibung
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    beschreibung: prismicT.RichTextField;
    /**
     * Entsehungszeitpunkt field in *EintragChronologie → Items*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: eintrag_chronologie.items[].entsehungszeitpunkt
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    entsehungszeitpunkt: prismicT.DateField;
    /**
     * Projektlink field in *EintragChronologie → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: eintrag_chronologie.items[].projektlink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    projektlink: prismicT.LinkField;
}
/**
 * Default variation for EintragChronologie Slice
 *
 * - **API ID**: `default`
 * - **Description**: `EintragChronologie`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type EintragChronologieSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<EintragChronologieSliceDefaultItem>>;
/**
 * Slice variation for *EintragChronologie*
 *
 */
type EintragChronologieSliceVariation = EintragChronologieSliceDefault;
/**
 * EintragChronologie Shared Slice
 *
 * - **API ID**: `eintrag_chronologie`
 * - **Description**: `EintragChronologie`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type EintragChronologieSlice = prismicT.SharedSlice<"eintrag_chronologie", EintragChronologieSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ChronologieDocumentData, ChronologieDocumentDataSlicesSlice, ChronologieDocument, CvDocumentData, CvDocument, ImpressumDocumentData, ImpressumDocument, KontaktDocumentData, KontaktDocument, ProjektDocumentData, ProjektDocument, ProjektkategorieDocumentData, ProjektkategorieDocument, WerkDocumentData, WerkDocumentDataSlicesSlice, WerkDocument, AllDocumentTypes, ImageUploaderSliceDefaultItem, ImageUploaderSliceDefault, ImageUploaderSliceVariation, ImageUploaderSlice, EintragChronologieSliceDefaultItem, EintragChronologieSliceDefault, EintragChronologieSliceVariation, EintragChronologieSlice };
    }
}
