// Code generated by Slice Machine. DO NOT EDIT.

import BilderHochladen from './BilderHochladen';
import EintragChronologie from './EintragChronologie';
import Projektkategorien from './Projektkategorien';

export {
	BilderHochladen,
	EintragChronologie,
	Projektkategorien,
};

export const components = {
	image_uploader: BilderHochladen,
	eintrag_chronologie: EintragChronologie,
	werkkategorie: Projektkategorien,
};
