// Code generated by Slice Machine. DO NOT EDIT.

import BilderHochladen from './BilderHochladen';
import EintragChronologie from './EintragChronologie';

export {
	BilderHochladen,
	EintragChronologie,
};

export const components = {
	image_uploader: BilderHochladen,
	eintrag_chronologie: EintragChronologie,
};
