// Code generated by Slice Machine. DO NOT EDIT.

import BilderHochladen from './BilderHochladen';
import EintragChronologie from './EintragChronologie';
import Projektkategorien from './Projektkategorien';
import VideosHochladen from './VideosHochladen';

export {
	BilderHochladen,
	EintragChronologie,
	Projektkategorien,
	VideosHochladen,
};

export const components = {
	image_uploader: BilderHochladen,
	eintrag_chronologie: EintragChronologie,
	werkkategorie: Projektkategorien,
	video_hochladen: VideosHochladen,
};
